-- AlterTable
ALTER TABLE `Notification` MODIFY `type` ENUM('MENTION', 'TEAM_INVITE', 'LOW_ATTENDANCE', 'MEETING_CREATED', 'MEETING_DELETED', 'MEETING_UPDATED', 'DEADLINE_OVERRIDE_GRANTED', 'TEAM_HEALTH_SUBMITTED', 'FORUM_REPLY', 'FORUM_REPORTED') NOT NULL;
