import type { SeedHelpArticle, SeedHelpTopic } from "./types";

export const helpTopics: SeedHelpTopic[] = [
  { slug: "overview", title: "Overview", sortOrder: 1 },
  {
    slug: "getting-started",
    title: "Getting Started",
    description: "Profile setup, modules, and your first project steps.",
    sortOrder: 2,
  },
  {
    slug: "account-access",
    title: "Account & Access",
    description: "Sign-in issues, missing modules, and account recovery.",
    sortOrder: 3,
  },
  {
    slug: "roles-permissions",
    title: "Roles & Permissions",
    description: "What students, staff, and admins can do.",
    sortOrder: 4,
  },
  { slug: "faqs", title: "FAQs", description: "Search and browse the full knowledge base.", sortOrder: 5 },
  { slug: "support", title: "Support", description: "Contact support and report issues.", sortOrder: 6 },
];

export const helpArticles: SeedHelpArticle[] = [
  {
    slug: "help-overview",
    topicSlug: "overview",
    title: "Help Center Overview",
    summary: "This help center is organized by topic for common tasks and troubleshooting.",
    sortOrder: 1,
    body: [
      "This help center is organized by topic. Use the tabs above to switch between Getting Started, Account & Access, Roles & Permissions, FAQs, and Support.",
      "",
      "Coverage: Guides for students, staff, and admins.",
      "Knowledge Base: Searchable FAQs and task-based walkthroughs.",
      "Support: Email support@teamfeedback.app for urgent issues.",
      "",
      "Browse by topic to find role-specific onboarding, account recovery guidance, permission explanations, or support contact details.",
    ].join("\n"),
  },
  {
    slug: "getting-started-playbook",
    topicSlug: "getting-started",
    title: "Getting Started",
    summary: "Start with the steps that match your role in the workspace.",
    sortOrder: 1,
    body: [
      "Students",
      "- Open your profile from the user menu and confirm your details.",
      "- Go to Modules to review your active module spaces and deadlines.",
      "- Go to Projects to view team activity, meetings, and assessments.",
      "Tip: Use the Calendar to keep track of upcoming meetings and submission deadlines.",
      "",
      "Staff",
      "- Confirm your profile details and notification preferences.",
      "- Open Staff -> Projects to review your active teaching spaces.",
      "- Open Staff -> Questionnaires to create or reuse assessment templates.",
      "Tip: Check Team allocation and Meetings to keep cohorts on schedule.",
      "",
      "Admins",
      "- Confirm your profile details and workspace settings.",
      "- Open Admin -> Users to verify roles and access assignments.",
      "- Review Enterprise -> Feature flags and Admin -> Enterprises if your workspace uses them.",
      "Tip: Use the Audit log to verify changes and keep access aligned with policy.",
    ].join("\n"),
  },
  {
    slug: "account-access-guide",
    topicSlug: "account-access",
    title: "Account & Access",
    sortOrder: 1,
    body: [
      "Access issues",
      "- If a module or project is missing, ask a staff lead or admin to verify your assignment.",
      "- If you cannot sign in, use the Forgot password flow from the login page.",
      "",
      "Login & recovery",
      '- The login screen includes a "Forgot password?" link that emails a reset link.',
      "- If your account is suspended, contact support or your workspace admin to restore access.",
    ].join("\n"),
  },
  {
    slug: "roles-permissions-guide",
    topicSlug: "roles-permissions",
    title: "Roles & Permissions",
    summary: "Each role unlocks different capabilities in the platform.",
    sortOrder: 1,
    body: [
      "Role overview",
      "- Student: Access your team spaces, submissions, and assigned workflows.",
      "- Staff: Manage teaching workflows, assessments, and module operations.",
      "- Enterprise Admin: Manage enterprise-level workspaces and settings.",
      "- Admin: Manage platform-wide users, permissions, and operational controls.",
      "",
      "Access rules",
      "- Access to staff and admin areas is restricted to those roles.",
      "- If you see a permission error, your role may not include that area. Contact your admin to confirm access.",
    ].join("\n"),
  },
  {
    slug: "faq-guide",
    topicSlug: "faqs",
    title: "Frequently Asked Questions",
    summary: "Search and browse the full knowledge base by audience and workflow.",
    audience: "GENERAL",
    sortOrder: 1,
    body: [
      "The FAQ library is grouped into general, student, staff, and enterprise admin questions.",
      "",
      "Use it for quick answers on modules, projects, questionnaires, access, deadlines, and support processes.",
    ].join("\n"),
  },
  {
    slug: "support-guide",
    topicSlug: "support",
    title: "Support",
    summary: "Get in touch with the support team.",
    sortOrder: 1,
    body: [
      "Contact support",
      "- For access issues, data concerns, or account problems, contact support.",
      "- Support is available by email at support@teamfeedback.app.",
      "",
      "Report a bug / request a feature",
      "- Include what happened, expected behavior, and steps to reproduce.",
      "- Attach screenshots and your module or project context to help diagnose quickly.",
    ].join("\n"),
  },
];
