
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const fallbackDatabaseUrl = "mysql://root:root@localhost:3306/reggie_dev";
const configuredDatabaseUrl = process.env.DATABASE_URL?.trim();
const databaseUrl = configuredDatabaseUrl ? configuredDatabaseUrl : fallbackDatabaseUrl;

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
  },
});
