import { defineConfig } from "vitest/config";
import path from "node:path";

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    include: ["src/**/*.test.ts", "src/**/*.test.*.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "lcov"],
      reportsDirectory: "coverage",
      reportOnFailure: true,
      exclude: [
        "scripts/**",
        "eslint.config.js",
        "vitest.config.ts",
        "**/*.test.ts",
        "**/*.test.*.ts",
        "**/types.ts",
        "**/*.types.ts",
        "prisma/seed/teamHealthScenario/**",
        "prisma/seed/team-health-warning-scenario.ts",
        // Legacy hotspots tracked outside current unit-test coverage gate.
        "src/features/audit/retentionJob.ts",
        "src/features/projects/project-manage/repo.ts",
        "src/features/forum/repo/reactions.ts",
        "src/features/projects/repo.staff-module-access.ts",
        "src/features/projects/repo.project-module-leads.ts",
        "src/features/projects/repo.module-staff.ts",
        "src/features/projects/repo.questionnaire.ts",
        "src/features/audit/sse.ts",
        "src/features/projects/repo.marking.ts",
        "src/shared/projectWriteGuard.ts",
        "src/features/projects/service.ts",
        "src/features/projects/project-manage/controller.ts",
        "src/features/projects/controller.modules.ts",
        "src/features/forum/repo/posts.ts",
        "src/features/projects/controller.handlers.ts",
        "src/features/forum/repo/access.ts",
        "src/features/forum/repo/studentReports.ts",
        "src/shared/rateLimit.ts",
        "src/features/warnings/evaluator.ts",
        "src/features/github/service.analysis.fetch.ts",
        "src/features/github/oauth.service.ts",
        "src/features/github/controller.snapshots.ts",
        "src/features/github/controller.live.ts",
        "src/features/github/service.analysis.link-header.ts",
        "src/features/github/controller.connect.ts",
        "src/features/audit/service.ts",
        "src/features/github/controller.links.ts",
        "src/features/team-health-review/service.ts",
        "src/features/peerFeedback/service.ts",
        "src/features/projects/repo.project-write.ts",
        "src/features/github/service.analysis.run.ts",
        "src/features/warnings/service.ts",
        "src/features/github/oauth.return-to.ts",
        "src/features/team-health-review/controller.messages.ts",
        "src/features/peerAssessment/controller.ts",
        "src/features/help/service.ts",
        "src/features/peerAssessment/answers.ts",
        "src/features/peerFeedback/controller.ts",
        "src/features/projects/repo.modules.ts",
        "src/features/github/service.live.ts",
        "src/features/github/controller.parsers.ts",
        "src/features/github/service.analysis.aggregate.ts",
        "src/features/peerAssessment/repo.ts",
        "src/features/teamAllocation/repo/repo.drafts.reads.ts",
        "src/features/meetings/service.attendance.ts",
        "src/features/projects/repo.staff-projects.ts",
        "src/features/teamAllocation/repo/repo.scope.ts",
        "src/features/projects/nav-flags/service.ts",
        "src/features/peerAssessment/staff/service.performanceSummary.ts",
        "src/features/admin/controller.parsers.ts",
        "src/features/projects/repo.staff-project-teams.ts",
        "src/features/teamAllocation/repo/repo.project-access.ts",
        "src/features/teamAllocation/repo/repo.drafts.writes.ts",
        "src/features/forum/controller.ts",
        "src/features/meetings/service.comments.ts",
        "src/features/teamAllocation/service/service.invites.ts",
        "src/features/calendar/service.ts",
        "src/features/github/service.analysis.commit-stats.ts",
        "src/features/peerFeedback/repo.ts",
        "src/features/forum/controller.parsers.ts",
      ],
      thresholds: {
        lines: 90,
        functions: 90,
        branches: 90,
        statements: 90,
      }
    },
    alias: {
      "@": path.resolve(__dirname, "src"),
    },
  },
});
